"""
Report generation service.
Supports Markdown (pure text) and PDF (via fpdf2).
"""
from datetime import datetime
from typing import List
from fpdf import FPDF
import os, tempfile

from app.db.models.osint import Search, Finding, RiskLevel


def generate_markdown(search: Search, findings: List[Finding]) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %Human:%M UTC")
    risk_badge = {
        "high": "🔴 HIGH",
        "medium": "🟡 MEDIUM",
        "low": "🟢 LOW",
        "unknown": "⚪ UNKNOWN",
    }.get(search.risk_level.value, "⚪")

    lines = [
        f"# OSINT Intelligence Report",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Entity** | {search.query} |",
        f"| **Type** | {search.entity_type.value.title()} |",
        f"| **Risk Level** | {risk_badge} |",
        f"| **Risk Score** | {search.risk_score:.0%} |",
        f"| **Confidence** | {search.confidence_score:.0%} |",
        f"| **Generated** | {now} |",
        f"",
        f"## Executive Summary",
        f"",
        f"{search.summary or 'No summary available.'}",
        f"",
    ]

    categories = {}
    for f in findings:
        categories.setdefault(f.category, []).append(f)

    category_order = ["social", "technical", "regulatory"]
    category_labels = {
        "social": "Social & Public Footprint",
        "technical": "Technical Infrastructure",
        "regulatory": "Contextual & Regulatory",
    }

    for cat in category_order:
        if cat not in categories:
            continue
        lines += [
            f"## {category_labels.get(cat, cat.title())}",
            f"",
        ]
        for f in categories[cat]:
            mock_tag = " *(simulated)*" if f.is_mock else ""
            risk_icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(f.risk_level.value, "⚪")
            lines += [
                f"### {f.title}{mock_tag}",
                f"",
                f"- **Source**: {f.adapter}  ",
                f"- **Risk**: {risk_icon} {f.risk_level.value.title()}  ",
                f"- **Confidence**: {f.confidence:.0%}  ",
                f"- **Fetched**: {f.fetched_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
                f"",
                f"{f.description or ''}",
                f"",
            ]
            if f.source_url:
                lines.append(f"[View source]({f.source_url})")
            lines.append("")

    lines += [
        "---",
        f"*Generated by OSINT Intelligence Platform · {now}*",
        "",
        "> **Disclaimer**: Data sourced from public APIs and open databases.",
        "> Mock/simulated entries are clearly marked.",
    ]
    return "\n".join(lines)


#pdf report
class OSINTPdf(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 60)
        self.cell(0, 10, "OSINT Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(100, 100, 200)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"OSINT Intelligence Platform  ·  Page {self.page_no()}", align="C")


RISK_COLORS = {
    "high":    (220, 53,  69),
    "medium":  (255, 193, 7),
    "low":     (40,  167, 83),
    "unknown": (108, 117, 125),
}


def generate_pdf(search: Search, findings: List[Finding]) -> str:
    """Generate a PDF report and return the file path."""
    pdf = OSINTPdf()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    risk_color = RISK_COLORS.get(search.risk_level.value, (108, 117, 125))

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 7, f"Entity: {search.query}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Type: {search.entity_type.value.title()}    "
                   f"Risk Score: {search.risk_score:.0%}    "
                   f"Confidence: {search.confidence_score:.0%}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(*risk_color)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(40, 7, f"  {search.risk_level.value.upper()} RISK",
             fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 7, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 5, search.summary or "No summary available.")
    pdf.ln(4)

    categories: dict[str, List[Finding]] = {}
    for f in findings:
        categories.setdefault(f.category, []).append(f)

    category_order = ["social", "technical", "regulatory"]
    category_labels = {
        "social": "Social & Public Footprint",
        "technical": "Technical Infrastructure",
        "regulatory": "Contextual & Regulatory",
    }

    for cat in category_order:
        if cat not in categories:
            continue

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 60)
        pdf.set_fill_color(230, 230, 245)
        pdf.cell(0, 8, f"  {category_labels.get(cat, cat.title())}",
                 fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for f in categories[cat]:
            rc = RISK_COLORS.get(f.risk_level.value, (108, 117, 125))

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 60)
            title = f.title[:90] + ("..." if len(f.title) > 90 else "")
            pdf.multi_cell(0, 6, title)

            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*rc)
            pdf.cell(0, 5,
                f"Risk: {f.risk_level.value.upper()}  |  "
                f"Confidence: {f.confidence:.0%}  |  "
                f"Source: {f.adapter}  |  "
                f"{'[Simulated] ' if f.is_mock else ''}"
                f"{f.fetched_at.strftime('%Y-%m-%d %H:%M UTC')}",
                new_x="LMARGIN", new_y="NEXT"
            )

            if f.description:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 5, f.description[:400])

            if f.source_url:
                pdf.set_font("Helvetica", "U", 8)
                pdf.set_text_color(0, 100, 200)
                pdf.cell(0, 5, f.source_url[:100], new_x="LMARGIN", new_y="NEXT")

            pdf.ln(3)

    tmp = tempfile.NamedTemporaryFile(
        delete=False, suffix=".pdf", prefix=f"osint_{search.id}_"
    )
    pdf.output(tmp.name)
    return tmp.name
